name=Vader3 Gamepad Library
version=1.0.0
author=Iurii(hol1tik)
maintainer=Iurii(hol1tik)
sentence=Library for Vader 3 Pro BLE gamepad
paragraph=Easy to use wrapper for Vader 3 Pro BLE gamepad. Provides simple button press detection and analog stick values.
category=Device Control
url=https://github.com/YuriyGolinkovskiy/esp32_vader3_gamepad_library
architectures=esp32